/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rouies_remotedesktop_decompress_LZODecompresor */

#ifndef _Included_com_rouies_remotedesktop_decompress_LZODecompresor
#define _Included_com_rouies_remotedesktop_decompress_LZODecompresor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rouies_remotedesktop_decompress_LZODecompresor
 * Method:    compress
 * Signature: ([BI)V
 */
JNIEXPORT jint JNICALL Java_com_rouies_remotedesktop_decompress_LZODecompresor_compress
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_rouies_remotedesktop_decompress_LZODecompresor
 * Method:    decompress
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_rouies_remotedesktop_decompress_LZODecompresor_decompress
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
